# build an elastic stack (elasticsearch, kibana, filebeat) 
version: '2'
services:
  # build elasticsearch, and call it es01 
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # store elasticsearch data on the host
      - data01:/usr/share/elasticsearch/data
      # get the elasticsearch config file from the host
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - elastic
  # filebeat config 
  filebeat:
    user: root
    networks:
      - elastic
    image: docker.elastic.co/beats/filebeat:7.7.1
    volumes:
      # mount /var/log from host system, and share with container.  
      #- /var/log/:/var/log/
      # filebeat config file lives on the host
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # allow the suricata filebeat module to be customized, and share with filebeat
      - ./filebeat/modules/suricata/suricata.yml:/usr/share/filebeat/modules.d/suricata.yml
      - ./suricata/logs/:/var/log/suricata/
      
    restart: on-failure
# start kibana 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/plugins:/usr/share/kibana/x-pack/plugins/
    networks:
      - elastic
    ports:
      - 5601:5601

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
