# build an elastic stack (elasticsearch, kibana, filebeat) 
version: '2'
services:
# Suricata IDS 
  suricata:
    image: docker.io/cifranix/suricata:4.1.2
    container_name: suricata
    volumes:
      # A directory for logs 
      - ./suricata/logs/:/var/log/suricata/
      # configuration file directory 
      - ./suricata/etc/:/etc/suricata/ 
      # rule file 
      - ./suricata/rules/suricata.rules:/var/lib/suricata/rules/suricata.rules
    network_mode: host
    # the SURICATA_INT variable is stored in the '.env' file within the repo 
    command: bash -c "echo ${SURICATA_INT} && /usr/bin/suricata -c /etc/suricata/suricata.yaml -i ${SURICATA_INT} --init-errors-fatal"
